# Generated by Django 3.1.4 on 2022-01-17 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('name', models.CharField(max_length=52)),
                ('symbol', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('chart_symbol', models.CharField(max_length=2222)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ask', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('img', models.CharField(max_length=23445)),
                ('group', models.CharField(max_length=70)),
                ('popular', models.BooleanField(default=False)),
                ('change', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('spread_diff', models.IntegerField(default=0)),
                ('digits', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='Enter description...', null=True)),
                ('contract_size', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('instrument', models.IntegerField(default=0)),
                ('volume_min', models.IntegerField(default=1)),
                ('volume_max', models.IntegerField(default=3000)),
                ('volume_step', models.IntegerField(default=1)),
                ('tick_size', models.IntegerField(default=0)),
                ('tick_value', models.IntegerField(default=0)),
                ('margin_initial', models.IntegerField(default=0)),
                ('mode', models.IntegerField(default=0)),
                ('profit_mode', models.IntegerField(default=0)),
                ('market_state', models.IntegerField(default=0)),
                ('stops_level', models.IntegerField(default=0)),
                ('lots_currency', models.CharField(default='USD', max_length=6)),
                ('display_name', models.CharField(max_length=220)),
                ('mover', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Wallet Balance')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tranaction Amount')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('CLOSE', 'Trade Close'), ('DEPO', 'Deposit'), ('WITHD', 'Withdrawal')], default='WITHD', max_length=5)),
                ('transaction_status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PROCESSING', max_length=10)),
                ('email', models.CharField(max_length=555, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_withdraw_transaction', to='trade.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TradeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField(auto_now=True)),
                ('asset_name', models.CharField(max_length=32)),
                ('asset_volume', models.IntegerField(default=0)),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('open_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leverage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stop_loss_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stop_loss_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_trade_open', models.BooleanField(default=True)),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(max_length=555, null=True)),
                ('symbol', models.CharField(max_length=32, null=True)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tradetransaction', to='trade.wallet')),
            ],
        ),
    ]
