# Generated by Django 3.1.4 on 2021-12-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ask',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='change',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='asset',
            name='chart_symbol',
            field=models.CharField(default='asdf', max_length=2222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='group',
            field=models.CharField(default='Forex', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='image_url',
            field=models.CharField(default='asderf', max_length=23445),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
