# Generated by Django 3.1.4 on 2022-01-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20211230_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='image_url',
            new_name='img',
        ),
        migrations.AddField(
            model_name='asset',
            name='clear_name',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='contract_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000000),
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, default='Enter description...', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='digits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='instrument',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='lots_currency',
            field=models.CharField(default='USD', max_length=6),
        ),
        migrations.AddField(
            model_name='asset',
            name='margin_initial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='market_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='mover',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='profit_mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='spread_diff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='stops_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='tick_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='tick_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asset',
            name='volume_max',
            field=models.IntegerField(default=3000),
        ),
        migrations.AddField(
            model_name='asset',
            name='volume_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='asset',
            name='volume_step',
            field=models.IntegerField(default=1),
        ),
    ]
