# Generated by Django 3.1.4 on 2022-01-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20220108_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='clear_name',
        ),
        migrations.AddField(
            model_name='asset',
            name='display_name',
            field=models.CharField(default='BSUSD', max_length=220),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='group',
            field=models.CharField(max_length=70),
        ),
    ]
