# Generated by Django 3.1.4 on 2021-11-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20211127_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('name', models.CharField(max_length=52)),
                ('symbol', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='tradetransaction',
            name='trade_status',
        ),
        migrations.AddField(
            model_name='tradetransaction',
            name='is_trade_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tradetransaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_open_close', to='trade.wallet'),
        ),
        migrations.AddField(
            model_name='tradetransaction',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='trade.asset'),
        ),
    ]
