# Generated by Django 3.1.4 on 2022-01-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20220108_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='contract_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
