# Generated by Django 3.1.4 on 2021-11-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20211130_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradetransaction',
            name='leverage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
