# Generated by Django 3.1.4 on 2021-11-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20211130_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradetransaction',
            name='symbol',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
