# Generated by Django 3.1.4 on 2021-12-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_auto_20211130_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('CLOSE', 'Trade Close'), ('DEPO', 'Deposit'), ('WITHD', 'Withdrawal')], default='WITHD', max_length=5),
        ),
    ]
