# Generated by Django 3.1.4 on 2021-12-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igmcaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
