# Generated by Django 3.1.4 on 2021-11-27 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igmcaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(max_length=500)),
                ('currency', models.CharField(choices=[('C$', 'CAD'), ('$', 'USD'), ('A$', 'AUD'), ('£', 'GBP'), ('€', 'EURO'), ('CHF', 'CHF')], default='', max_length=3)),
                ('phone_number', models.CharField(max_length=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
