# Generated by Django 3.1.4 on 2021-12-08 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igmcaccount', '0003_auto_20211129_0217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
